apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: redis
  namespace: docker-registry
spec:
  selector:
    matchLabels:
      app: redis
  replicas: 2
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: master
        image: k8s.gcr.io/redis
        ports:
        - containerPort: 6379
